"use client";

import { useState } from "react";
import exifr from "exifr";
import { Button } from "@/components/ui/button";
import { Dropzone } from "@/components/tools/dropzone";
import { validateFiles } from "@/lib/files";
import { Loader2, Trash2, ScanSearch, Download } from "lucide-react";
import type { MediaToolDefinition } from "@/lib/media/tools";
import { ToolPanel } from "@/components/tools/tool-ui";
import { FilePill } from "@/components/tools/shared";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

function formatValue(val: any): string {
  if (val === null || val === undefined) return "null";
  if (val instanceof Date) return val.toISOString();
  if (Array.isArray(val) || val instanceof Uint8Array || val instanceof Uint16Array) {
    if (val.length > 20) return `[Array of ${val.length} items]`;
    return JSON.stringify(Array.from(val));
  }
  if (typeof val === "object") return JSON.stringify(val);
  return String(val);
}

function MetadataValue({ value }: { value: any }) {
  if (value === null || value === undefined) return <span>null</span>;
  if (value instanceof Date) return <span>{value.toISOString()}</span>;
  
  if (Array.isArray(value) || value instanceof Uint8Array || value instanceof Uint16Array) {
    if (value.length > 20) {
      return (
        <details className="group">
          <summary className="cursor-pointer text-primary hover:underline select-none inline-block">
            [Array of {value.length} items]
          </summary>
          <div className="mt-2 max-h-40 overflow-auto rounded border border-border bg-muted/50 p-2 text-[10px] break-words whitespace-pre-wrap">
            {JSON.stringify(Array.from(value))}
          </div>
        </details>
      );
    }
    return <span>{JSON.stringify(Array.from(value))}</span>;
  }
  
  if (typeof value === "object") return <span>{JSON.stringify(value)}</span>;
  return <span>{String(value)}</span>;
}

export function InspectRunner({ tool }: { tool: MediaToolDefinition }) {
  const [file, setFile] = useState<File | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [metadata, setMetadata] = useState<Record<string, any> | null>(null);

  function add(files: File[]) {
    const { valid, error } = validateFiles(files, {
      accept: tool.accept,
      multiple: false,
      maxSizeMb: tool.maxSizeMb,
    });
    if (error) {
      setErr(error);
      return;
    }
    setErr(null);
    const f = valid[0];
    setFile(f);
    extractMetadata(f);
  }

  async function extractMetadata(f: File) {
    setLoading(true);
    try {
      // Parse EXIF, TIFF, IPTC, XMP, ICC all at once
      const data = await exifr.parse(f, {
        tiff: true,
        xmp: true,
        icc: true,
        iptc: true,
        exif: true,
        gps: true,
      });
      setMetadata(data || {});
    } catch (e: any) {
      setMetadata({}); // Fallback to empty if nothing parseable
    } finally {
      setLoading(false);
    }
  }

  function reset() {
    setFile(null);
    setErr(null);
    setMetadata(null);
  }

  function downloadPdf() {
    if (!metadata || !file) return;
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(16);
    doc.text(`Metadata Report: ${file.name}`, 14, 20);
    
    // Add file info
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by FreeOfficeTools`, 14, 27);
    
    // Convert metadata object into array of rows
    const rows = Object.entries(metadata).map(([key, value]) => [
      key, 
      formatValue(value)
    ]);
    
    // Generate table
    autoTable(doc, {
      startY: 35,
      head: [['Property', 'Value']],
      body: rows,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      styles: { fontSize: 8, cellPadding: 3, overflow: 'linebreak' },
      columnStyles: {
        0: { cellWidth: 50, fontStyle: 'bold' },
        1: { cellWidth: 'auto' }
      }
    });
    
    // Save PDF
    doc.save(`${file.name.replace(/\.[^/.]+$/, "")}-metadata.pdf`);
  }

  // Determine if empty metadata
  const hasMeta = metadata && Object.keys(metadata).length > 0;

  return (
    <ToolPanel>
      <div className="flex items-center justify-between p-6">
        <div>
          <h2 className="text-xl font-semibold leading-none tracking-tight">{tool.h1}</h2>
          <p className="mt-2 text-sm text-muted-foreground">{tool.heroSubtitle}</p>
        </div>
      </div>

      <div className="border-t border-border bg-muted/30 p-6">
        {!file && (
          <div className="space-y-4">
            {err && <div className="text-sm font-medium text-destructive">{err}</div>}
            <Dropzone
              onFiles={add}
              multiple={false}
              accept={tool.accept}
              acceptLabel={tool.acceptLabel}
            />
          </div>
        )}

        {file && !metadata && loading && (
          <div className="flex min-h-[200px] flex-col items-center justify-center space-y-4 rounded-xl border border-dashed border-border bg-background p-6">
            <Loader2 className="size-6 animate-spin text-muted-foreground" />
            <p className="text-sm font-medium">Extracting hidden metadata...</p>
          </div>
        )}

        {file && metadata && (
          <div className="space-y-6">
            <div className="flex items-center justify-between">
              <FilePill name={file.name} size={file.size} onRemove={reset} />
              <div className="flex gap-2">
                <Button variant="outline" size="sm" onClick={reset}>
                  <Trash2 className="mr-2 size-4" />
                  Clear
                </Button>
                {hasMeta && (
                  <Button size="sm" onClick={downloadPdf}>
                    <Download className="mr-2 size-4" />
                    Download as PDF
                  </Button>
                )}
              </div>
            </div>

            {hasMeta ? (
              <div className="rounded-xl border border-border bg-background shadow-sm overflow-hidden">
                <div className="border-b border-border bg-muted/50 px-4 py-3">
                  <h3 className="font-semibold text-sm">Extracted Metadata Tags</h3>
                </div>
                <div className="max-h-[500px] overflow-auto">
                  <table className="w-full text-sm text-left">
                    <thead className="bg-muted/30 sticky top-0 backdrop-blur">
                      <tr>
                        <th className="px-4 py-2 font-medium text-muted-foreground border-b border-border">Property</th>
                        <th className="px-4 py-2 font-medium text-muted-foreground border-b border-border">Value</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border">
                      {Object.entries(metadata).map(([key, value]) => (
                        <tr key={key} className="hover:bg-muted/20 transition-colors">
                          <td className="px-4 py-3 font-medium font-mono text-xs w-1/3 whitespace-nowrap overflow-hidden text-ellipsis">{key}</td>
                          <td className="px-4 py-3 font-mono text-xs break-words break-all text-muted-foreground">
                            <MetadataValue value={value} />
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ) : (
              <div className="flex min-h-[150px] flex-col items-center justify-center rounded-xl border border-dashed border-border bg-background p-6 text-center">
                <div className="rounded-full bg-green-500/10 p-3 text-green-500 mb-3">
                  <ScanSearch className="size-6" />
                </div>
                <h3 className="text-sm font-semibold">No Metadata Found</h3>
                <p className="text-sm text-muted-foreground mt-1">This image is completely clean. No hidden tags, GPS coordinates, or AI prompts were detected.</p>
              </div>
            )}
          </div>
        )}
      </div>
    </ToolPanel>
  );
}
